## 7. Exception Handling

#### 구문 오류와 예외

갖가지 에러들을 디버거와 컴파일러를 사용하면서 봐왔기에,

사실은 익숙하면서도, 공부하는 입장에서는 자세하게 적용해 보기는 어려운 주제였다

실무에서는 많이 쓴다고 한다

.

오류에는 **구문 오류**와 **예외**가 있다

.

코드가 실행조차 되지 않는 오류를 **구문 오류(syntax error)**라고 한다

프로그램 실행 전에 발생한다

.

코드 실행 중간에 발생하는 오류를 **예외(exception)** 또는 **런타임 오류(runtime error)**라고 한다

프로그램 실행 중에 발생한다 **(TypeError, ReferenceError, RangError)**

.

구문 오류는 오류의 위치를 사전에 정확하게 짚어서 알려주기 때문에

비교적 쉽게 해결 할 수 있다

하지만 런타임 오류는 워낙에 방향이 다양하고 명확하지도 않다

그래서 이런 예외가 일어났을 경우에 코드를 미리 짜두는게 좋다

이걸 **예외 처리**라고 한다

.

조건문을 사용해서 문제가 발생할 수 있는 부분을 처리해 주는 것을

**기본 예외 처리**라고 한다

.

**try catch finally** 구문을 이용해 예외를 처리하는 방법을

**고급 예외 처리**라고 한다

catch와 finally 둘 중 하나는 생략 될 수 있다

솔직히 어떨 때 써야 할지 아직 잘은 모르겠다

.

기본적으로는 편하다고 생각하는 방법을 사용하면 되고,

예외를 예측하기 힘들다면 고급 예외 처리로 해주는게 좋다고 한다

.

#### 예외 처리 고급

고급이라고 해서 살짝 쫄았는데 어려운 내용은 딱히 없다

.

예외의 발생된 정보를 확인할 수 있게 해주는 걸 **예외 객체(exception object)**라고 한다

try catch finally 구문에서 catch의 괄호안에 식별자를 선언하므로서 사용 할 수 있다

보통 식별자는 e아님 exception을 쓴다고 함

예외 객체를 통해 예외의 이름과 메시지를 받을 수 있다

.

예외를 강제로 발생 시킬 때 **throw**를 쓴다

예외를 강제로 발생시켜 사용자에게 주의를 주고, 의도한 대로 처리하게 유도할 수 있다
